name: Release Build

on:
  pull_request:
    branches:
      - main
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Get inside the example folder
        run: cd examples/simple

      - name: Install dependencies
        run: pio lib install

      - name: Build
        run: pio run

      - name: create env variable for lib version from library.json
        id: lib_version
        run: echo "::set-output name=version::$(cat library.json | grep "version" | cut -d '"' -f 4)" 
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.lib_version.outputs.version }}
          release_name: Release ${{ steps.lib_version.outputs.version }}
          draft: false
          prerelease: false
          artifacts: examples/simple/.pio/build/release/*.bin, examples/simple/.pio/build/release/*.elf, examples/simple/.pio/build/release/*.hex